<a href="https://colab.research.google.com/github/smpark0520/ESAA/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%99%84%EB%B2%BD_%EA%B0%80%EC%9D%B4%EB%93%9C_pg_1~38.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이(Numpy)


*   Numerical Python의 약자, 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원함
*   배열 기반의 연산을 물론이고 다양한 데이터 핸들링 기능을 제공함

In [ ]:
import numpy as np

- 넘파이 모듈 임포드
- 넘파이 기반 데이터 타입 : ndarray -> 다차원 배열을 쉽게 생성하고 다양한 연산 수행 가능
- np.array() :  ndarray로 변환
- ndarray.shape() : ndarray 배열의 차원과 크기를 튜플 형태로 나타내줌

In [ ]:
array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2=np.array([[1,2,3],
                [2,3,4]])
print('array1 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array1 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


- array1 array 형태: (3,) -> 1차원 array, 3개의 데이터를 가지고 있음
- array2 array 형태: (2, 3) -> 2차원 array, 2개의 row & 3개의 column으로 구성되어 6개의 데이터를 가지고 있음
- array3 array 형태: (1, 3) -> 2차원이며, 1개의 row와 3개의 column으로 구성됨

In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


- 리스트 []는 1차원, 리스트의 리스트인 [[ ]]는 2차원!

# ndarray의 데이터 타입


*   숫자, 문자역, 불 값 모두 가능
*   숫자 -> int형, unsigned int형, float형, complex 타임(더 큰 숫자 값이나 정밀도)
- 같은 데이터 타입끼리만 연산 가능



In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- int형 값과 문자열이 섞여 있는 list2를 ndarray로 변환한 array2는 숫자 1,2가 모두 문자 1,2로 변환됨
- 모두 같은 데이터 타입이어야 하므로 다른 데이터 타입이 섞여 있을 경우 더 큰 데이터 타입으로 변환되기에 int형이 유니코드 문자열 값으로 변환
- list3의 경우 int형과 float형이 섞여 있는데, int인 1,2가 float64형으로 바뀜

- astype() : ndarray 내의 데이터값의 타입 변경
- astype()에 인자로 원하는 타입을 문자열로 지정
- 이렇게 하는 이유는, 메모리 절감이 가능하기 때문임

In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


- int32형 데이터를 float64로 변환하고, 다시 float64를 int32로 변경

# ndarray를 편리하게 생성하기 - arange, zeros, ones


*   주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용
*  arange() : array를 range()로 표현, 0부터 함수 인자 값-1까지의 값을 순차적으로 ndarray의 데이터값으로 변환



In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


- sequence_array : 0부터 (10-1 = )9까지의 연속 숫자 값으로 구성된 1차원 array

- zeros() : 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray로 반환
- ones() : 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray로 반환, dtype을 정해주지 않으면 default로 float64 형의 데이터로 ndarray를 채움

In [ ]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape()


*   reshape() : ndarray를 특정 차언 및 크기로 변환


In [ ]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- 0~9까지의 1차원 ndarray를 2 row x 5 col과 5 row x 2 col 형태로 2차원 ndarray로 변환

- (10,) 데이터를 (4,3) shape 형태로 변경할 수 없기에 오류 발생

In [ ]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2.shape:',array2.shape)
array3=array1.reshape(5,-1)
print('array3.shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2.shape: (2, 5)
array3.shape: (5, 2)


- array2=array1.reshape(-1,5) -> row인자가 -1, col인자가 5
- 10개의 1차원 데이터와 호환될 수 있는 고정된 5개 col에 맞는 row 개수는 2개이므로, 2 x 5의 2차원 ndarray로 변환
- array3=array1.reshape(5,-1) -> 10개의 1차원 데이터와 호환될 수 있는 고정된 5개의 row에 맞는 col은 2이므로 5 x 2의 2차원 ndarray로 변환

In [ ]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

- 하지만, 10개의 1차원 데이터롤 고정된 4개의 col을 가진 row로는 변경할 수 없기에 오류뜸

- reshape(-1,1) : 2차원, 여러 개의 row을 가지되 반드시 1개의 col을 가진 ndarray로 변환됨을 보장

In [ ]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array3d.reshape(-1,1)
print('array6:\n',array5.tolist())
print('array6 shape',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape (8, 1)


- reshape(-1,1)을 이용해 3차원을 2차원으로, 1차원을 2차원으로 변경
- ndarray는 tolist()를 이용해리스트 자료형으로 변환

# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)


*   특정 데이터만 추출
*   슬라이싱 : 연속된 인덱스상의 ndarray를 추출
- 팬시 인덱싱 : 일정한 인덱싱 집합을 list나 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray로 반환
- 불린 인덱싱 : True/False 인덱싱 집합을 기반으로 True에 해당하ㅡㄴ 인덱스 위치에 있는 데이터의 ndarray를 반환



In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print('array1:',array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


- array1[2] : 3번째 인덱스 위치의 데이터 값 = 3

In [ ]:
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:',array2d[0,0])
print('(row=0,col=1) index 가리키는 값:',array2d[0,1])
print('(row=1,col=0) index 가리키는 값:',array2d[1,0])
print('(row=2,col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


- 앞 예제의 1차원 ndarray를 2차원의 3x3 ndarray로 변환 후, [row, col]을 이용해 2차원 ndarray에서 데이터 추출
- array2d[0,0] : 첫 번째 row, 첫 번째 col 위치의 데이터인 1
- array2d[0,1] : 첫 번째 row, 두 번째 col 위치의 데이터인 2
- array2d[2,2] : 세 번째 row, 세 번째 col 위치의 데이터인 9
- axis 0 : row 방향의 축, axis 1 : col 방향의 축

In [ ]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


- 시작:종료 -> 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환

In [ ]:
array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2] \n',array2d[0:2,0:2])
print('array2d[1:3,0:3] \n',array2d[1:3,0:3])
print('array2d[1:3,:] \n',array2d[1:3,:])
print('array2d[:,:] \n',array2d[:,:])
print('array2d[:2,1:] \n',array2d[:2,1:])
print('array2d[:2,0] \n',array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape, 'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] =>',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] =>',array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


- array2d[ [0, 1] ,2] : row 축에 팬시 인덱싱인 [0, 1]을, col 축에는 단일 값 인덱싱 2를 적용 -> (0,2), (1,2)로 적용돼 [3, 6]을 반환
- array2d[ [0, 1], 0 : 2] : ((0, 0),(0, 1)),((1, 0),(1, 1)) 인덱싱이 적용돼 [[1, 2], [4, 5]]를 반환

In [ ]:
array1d=np.arange(start=1,stop=10)
#[] 안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


- [1, 2, 3, 4, 5, 6, 7, 8, 9]에서 데이터 값이 5보다 큰 데이터만 추출

In [ ]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

- 5보다 큰 데이터가 있는 위치는 True 값이, 그렇지 않은 부분은 False 값이 반환

In [ ]:
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱싱 결과:',array3)

불린 인덱싱 결과: [6 7 8 9]


In [ ]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


step1 : array1d > 5와 같이 ndarray의 필터링조건을 []안데 기재
step2 : False값은 무시하고 True값에 해당하는 인덱스값만 저장
step3 : 저장된 인덱스 데이터 세트로 ndarray 조회

# 행렬의 정렬 - sort()와 argsort()



- np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환, 변환값은 None

In [ ]:
org_array=([3,1,9,5])
print('원본 행렬:',org_array)
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np_sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np_sort() 호출 후 반환된 원본 행렬:',org_array)
#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array_sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array_sort() 호출 후 원본 행렬:',org_array)

원본 행렬: [3, 1, 9, 5]
np_sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np_sort() 호출 후 반환된 원본 행렬: [3, 1, 9, 5]
org_array_sort() 호출 후 반환된 행렬: None
org_array_sort() 호출 후 원본 행렬: [1, 3, 5, 9]


- 원본 행렬 [ 3 1 9 5 ] 에 대해서 np.sort()는 원본 행렬을 변경하지 않고 정렬된 형태로 반환했으며, ndarray.sort()는 원본 행렬 자체를 정렬한 값으로 변환함

In [ ]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d=np.array([[8,12],
                  [7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 워본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용
- np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환

In [ ]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
import numpy as np

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순 정렬 시 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순 정렬 시 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


- John = 78, Mike = 95, Sarah = 84, Kate = 98, Samuel = 88을 ndarray로 활용하고자 함
- 시험 성적 순으로 학생 이름을 출력하고자 한다면 np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스를 적용해 추출

# 선형대수 연산 = 행렬 내적과 전치 행렬 구하기

행렬 내적(행렬 곱)
- 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산

In [ ]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


전치 행렬
- 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
- transpose()를 이용해 구할 수 있음

In [ ]:
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
